JAVAC = javac

JCFLAGS = 

CLASSPOSTFIX = .class
JARPOSTFIX = .jar

RMFILECOMMAND = rm
COPYFILECOMMAND = cp
SLIBARCOMMAND = ar rcs

SILENT = >/dev/null
PATHSEPCHAR = /
JCLASSPATHSEPCHAR = :

osspeccleanwork:

osspecclean:

	find ./ -name "*.class" -exec rm {} \;