JAVAC = javac

JCFLAGS = 

CLASSPOSTFIX = .class
JARPOSTFIX = .jar

RMFILECOMMAND = del /q
COPYFILECOMMAND = xcopy /Y
SLIBARCOMMAND = 

SILENT = >/dev/null
PATHSEPCHAR = /
JCLASSPATHSEPCHAR = ;

osspeccleanwork:

osspecclean:

	del *.class /s